package com.project.forupets.model;
// Generated May 26, 2015 9:02:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblComment generated by hbm2java
 */
@Entity
@Table(name="tbl_comment"
    ,catalog="4upets"
)
public class TblComment  implements java.io.Serializable {


     private Integer commentId;
     private TblPost tblPost;
     private TblUser tblUser;
     private String content;
     private Date dateCreated;
     private Date dateUpdated;

    public TblComment() {
    }

	
    public TblComment(TblPost tblPost, TblUser tblUser, String content) {
        this.tblPost = tblPost;
        this.tblUser = tblUser;
        this.content = content;
    }
    public TblComment(TblPost tblPost, TblUser tblUser, String content, Date dateCreated, Date dateUpdated) {
       this.tblPost = tblPost;
       this.tblUser = tblUser;
       this.content = content;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="comment_id", unique=true, nullable=false)
    public Integer getCommentId() {
        return this.commentId;
    }
    
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="post_id", nullable=false)
    public TblPost getTblPost() {
        return this.tblPost;
    }
    
    public void setTblPost(TblPost tblPost) {
        this.tblPost = tblPost;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public TblUser getTblUser() {
        return this.tblUser;
    }
    
    public void setTblUser(TblUser tblUser) {
        this.tblUser = tblUser;
    }

    
    @Column(name="content", nullable=false,columnDefinition = "TEXT", length=65535)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_created", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_updated", length=19)
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }




}


