package com.project.forupets.model;
// Generated May 26, 2015 9:02:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblFollowing generated by hbm2java
 */
@Entity
@Table(name="tbl_following"
    ,catalog="4upets"
)
public class TblFollowing  implements java.io.Serializable {


     private Integer followingId;
     private TblUser tblUserByUserId;
     private TblUser tblUserByUserFollowId;
     private Date dateCreated;
     private Date dateUpdated;

    public TblFollowing() {
    }

	
    public TblFollowing(TblUser tblUserByUserId, TblUser tblUserByUserFollowId) {
        this.tblUserByUserId = tblUserByUserId;
        this.tblUserByUserFollowId = tblUserByUserFollowId;
    }
    public TblFollowing(TblUser tblUserByUserId, TblUser tblUserByUserFollowId, Date dateCreated, Date dateUpdated) {
       this.tblUserByUserId = tblUserByUserId;
       this.tblUserByUserFollowId = tblUserByUserFollowId;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="following_id", unique=true, nullable=false)
    public Integer getFollowingId() {
        return this.followingId;
    }
    
    public void setFollowingId(Integer followingId) {
        this.followingId = followingId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public TblUser getTblUserByUserId() {
        return this.tblUserByUserId;
    }
    
    public void setTblUserByUserId(TblUser tblUserByUserId) {
        this.tblUserByUserId = tblUserByUserId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_follow_id", nullable=false)
    public TblUser getTblUserByUserFollowId() {
        return this.tblUserByUserFollowId;
    }
    
    public void setTblUserByUserFollowId(TblUser tblUserByUserFollowId) {
        this.tblUserByUserFollowId = tblUserByUserFollowId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_created", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_updated", length=19)
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }




}


