package com.project.forupets.model;
// Generated May 26, 2015 9:02:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * TblHashtag generated by hbm2java
 */
@Entity
@Table(name="tbl_hashtag"
    ,catalog="4upets"
)
public class TblHashtag  implements java.io.Serializable {


     private int hashtagId;
     private TblTag tblTag;
     private String imageUrl;
     private String name;

    public TblHashtag() {
    }

	
    public TblHashtag(TblTag tblTag, String name) {
        this.tblTag = tblTag;
        this.name = name;
    }
    public TblHashtag(TblTag tblTag, String imageUrl, String name) {
       this.tblTag = tblTag;
       this.imageUrl = imageUrl;
       this.name = name;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="tblTag"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="hashtag_id", unique=true, nullable=false)
    public int getHashtagId() {
        return this.hashtagId;
    }
    
    public void setHashtagId(int hashtagId) {
        this.hashtagId = hashtagId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public TblTag getTblTag() {
        return this.tblTag;
    }
    
    public void setTblTag(TblTag tblTag) {
        this.tblTag = tblTag;
    }

    
    @Column(name="image_url", length=256)
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    
    @Column(name="name", nullable=false, length=128)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


