package com.project.forupets.model;
// Generated May 26, 2015 9:02:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblLike generated by hbm2java
 */
@Entity
@Table(name="tbl_like"
    ,catalog="4upets"
)
public class TblLike  implements java.io.Serializable {


     private Integer likeId;
     private TblPost tblPost;
     private TblUser tblUser;
     private Date dateCreated;
     private Date dateUpdated;

    public TblLike() {
    }

	
    public TblLike(TblPost tblPost, TblUser tblUser) {
        this.tblPost = tblPost;
        this.tblUser = tblUser;
    }
    public TblLike(TblPost tblPost, TblUser tblUser, Date dateCreated, Date dateUpdated) {
       this.tblPost = tblPost;
       this.tblUser = tblUser;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="like_id", unique=true, nullable=false)
    public Integer getLikeId() {
        return this.likeId;
    }
    
    public void setLikeId(Integer likeId) {
        this.likeId = likeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="post_id", nullable=false)
    public TblPost getTblPost() {
        return this.tblPost;
    }
    
    public void setTblPost(TblPost tblPost) {
        this.tblPost = tblPost;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public TblUser getTblUser() {
        return this.tblUser;
    }
    
    public void setTblUser(TblUser tblUser) {
        this.tblUser = tblUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_created", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_updated", length=19)
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }




}


