package com.project.forupets.model;
// Generated May 26, 2015 9:02:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblPost generated by hbm2java
 */
@Entity
@Table(name="tbl_post"
    ,catalog="4upets"
)
public class TblPost  implements java.io.Serializable {


     private Integer postId;
     private TblUser tblUser;
     private String caption;
     private Date dateCreated;
     private Date dateUpdated;
     private TblPhoto tblPhoto;
     private Set<TblTag> tblTags = new HashSet<TblTag>(0);
     private Set<TblLike> tblLikes = new HashSet<TblLike>(0);
     private Set<TblComment> tblComments = new HashSet<TblComment>(0);
     private TblVideo tblVideo;

    public TblPost() {
    }

    public TblPost(TblUser tblUser, String caption, Date dateCreated, Date dateUpdated, TblPhoto tblPhoto, Set<TblTag> tblTags, Set<TblLike> tblLikes, Set<TblComment> tblComments, TblVideo tblVideo) {
       this.tblUser = tblUser;
       this.caption = caption;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
       this.tblPhoto = tblPhoto;
       this.tblTags = tblTags;
       this.tblLikes = tblLikes;
       this.tblComments = tblComments;
       this.tblVideo = tblVideo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="post_id", unique=true, nullable=false)
    public Integer getPostId() {
        return this.postId;
    }
    
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public TblUser getTblUser() {
        return this.tblUser;
    }
    
    public void setTblUser(TblUser tblUser) {
        this.tblUser = tblUser;
    }

    
    @Column(name="caption", columnDefinition = "TEXT", length = 65535)
    public String getCaption() {
        return this.caption;
    }
    
    public void setCaption(String caption) {
        this.caption = caption;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_created", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_updated", length=19)
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="tblPost")
    public TblPhoto getTblPhoto() {
        return this.tblPhoto;
    }
    
    public void setTblPhoto(TblPhoto tblPhoto) {
        this.tblPhoto = tblPhoto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblPost")
    public Set<TblTag> getTblTags() {
        return this.tblTags;
    }
    
    public void setTblTags(Set<TblTag> tblTags) {
        this.tblTags = tblTags;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblPost")
    public Set<TblLike> getTblLikes() {
        return this.tblLikes;
    }
    
    public void setTblLikes(Set<TblLike> tblLikes) {
        this.tblLikes = tblLikes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblPost")
    public Set<TblComment> getTblComments() {
        return this.tblComments;
    }
    
    public void setTblComments(Set<TblComment> tblComments) {
        this.tblComments = tblComments;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="tblPost")
    public TblVideo getTblVideo() {
        return this.tblVideo;
    }
    
    public void setTblVideo(TblVideo tblVideo) {
        this.tblVideo = tblVideo;
    }




}


