package com.project.forupets.model;
// Generated May 26, 2015 9:02:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblPrivacy generated by hbm2java
 */
@Entity
@Table(name="tbl_privacy"
    ,catalog="4upets"
)
public class TblPrivacy  implements java.io.Serializable {


     private int privacyId;

    public TblPrivacy() {
    }

    public TblPrivacy(int privacyId) {
       this.privacyId = privacyId;
    }
   
     @Id 

    
    @Column(name="privacy_id", unique=true, nullable=false)
    public int getPrivacyId() {
        return this.privacyId;
    }
    
    public void setPrivacyId(int privacyId) {
        this.privacyId = privacyId;
    }




}


