package com.project.forupets.model;
// Generated May 26, 2015 9:02:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * TblPhoto generated by hbm2java
 */
@Entity
@Table(name="tbl_photo"
    ,catalog="4upets"
)
public class TblPhoto  implements java.io.Serializable {


     private int photoId;
     private TblPost tblPost;
     private String photoUrl;

    public TblPhoto() {
    }

	
    public TblPhoto(TblPost tblPost) {
        this.tblPost = tblPost;
    }
    public TblPhoto(TblPost tblPost, String photoUrl) {
       this.tblPost = tblPost;
       this.photoUrl = photoUrl;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="tblPost"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="photo_id", unique=true, nullable=false)
    public int getPhotoId() {
        return this.photoId;
    }
    
    public void setPhotoId(int photoId) {
        this.photoId = photoId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public TblPost getTblPost() {
        return this.tblPost;
    }
    
    public void setTblPost(TblPost tblPost) {
        this.tblPost = tblPost;
    }

    
    @Column(name="photo_url", length=256)
    public String getPhotoUrl() {
        return this.photoUrl;
    }
    
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl;
    }




}


