package com.project.forupets.model;
// Generated May 26, 2015 9:02:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * TblTagUser generated by hbm2java
 */
@Entity
@Table(name="tbl_tag_user"
    ,catalog="4upets"
)
public class TblTagUser  implements java.io.Serializable {


     private int tagUserId;
     private TblTag tblTag;
     private TblUser tblUser;

    public TblTagUser() {
    }

    public TblTagUser(TblTag tblTag, TblUser tblUser) {
       this.tblTag = tblTag;
       this.tblUser = tblUser;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="tblTag"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="tag_user_id", unique=true, nullable=false)
    public int getTagUserId() {
        return this.tagUserId;
    }
    
    public void setTagUserId(int tagUserId) {
        this.tagUserId = tagUserId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public TblTag getTblTag() {
        return this.tblTag;
    }
    
    public void setTblTag(TblTag tblTag) {
        this.tblTag = tblTag;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public TblUser getTblUser() {
        return this.tblUser;
    }
    
    public void setTblUser(TblUser tblUser) {
        this.tblUser = tblUser;
    }




}


