package com.project.forupets.model;
// Generated May 26, 2015 9:02:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblTag generated by hbm2java
 */
@Entity
@Table(name="tbl_tag"
    ,catalog="4upets"
)
public class TblTag  implements java.io.Serializable {


     private Integer tagId;
     private TblPost tblPost;
     private Date dateCreated;
     private Date dateUpdated;
     private TblHashtag tblHashtag;
     private TblTagUser tblTagUser;

    public TblTag() {
    }

    public TblTag(TblPost tblPost, Date dateCreated, Date dateUpdated, TblHashtag tblHashtag, TblTagUser tblTagUser) {
       this.tblPost = tblPost;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
       this.tblHashtag = tblHashtag;
       this.tblTagUser = tblTagUser;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tag_id", unique=true, nullable=false)
    public Integer getTagId() {
        return this.tagId;
    }
    
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="post_id")
    public TblPost getTblPost() {
        return this.tblPost;
    }
    
    public void setTblPost(TblPost tblPost) {
        this.tblPost = tblPost;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_created", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_updated", length=19)
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="tblTag")
    public TblHashtag getTblHashtag() {
        return this.tblHashtag;
    }
    
    public void setTblHashtag(TblHashtag tblHashtag) {
        this.tblHashtag = tblHashtag;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="tblTag")
    public TblTagUser getTblTagUser() {
        return this.tblTagUser;
    }
    
    public void setTblTagUser(TblTagUser tblTagUser) {
        this.tblTagUser = tblTagUser;
    }




}


