package com.project.forupets.model;
// Generated May 26, 2015 9:02:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * TblVideo generated by hbm2java
 */
@Entity
@Table(name="tbl_video"
    ,catalog="4upets"
)
public class TblVideo  implements java.io.Serializable {


     private int videoId;
     private TblPost tblPost;
     private String videoUrl;

    public TblVideo() {
    }

    public TblVideo(TblPost tblPost, String videoUrl) {
       this.tblPost = tblPost;
       this.videoUrl = videoUrl;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="tblPost"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="video_id", unique=true, nullable=false)
    public int getVideoId() {
        return this.videoId;
    }
    
    public void setVideoId(int videoId) {
        this.videoId = videoId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public TblPost getTblPost() {
        return this.tblPost;
    }
    
    public void setTblPost(TblPost tblPost) {
        this.tblPost = tblPost;
    }

    
    @Column(name="video_url", nullable=false, length=256)
    public String getVideoUrl() {
        return this.videoUrl;
    }
    
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }




}


